- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLoneAbductor
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: LoneAbductorAntag
    roleType: MinorAntagonist
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorAgent
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AbductorAgentAntag
    roleType: MinorAntagonist
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorScientist
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AbductorScientistAntag
    roleType: MinorAntagonist
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorVictim
  name: Abductee Role
  components:
  - type: MindRole
    roleType: FreeAgent
    antagPrototype: AbductorVictimAntag
  - type: AbductorVictim