#
## Static
- type: latheRecipePack
  id: SecurityAmmoStaticGoob
  recipes:
  - MagazineBoxShotgunHighCaliber
  - MagazineBoxShotgunSlugHighCaliber
  - MagazineBoxShotgunPracticeHighCaliber

- type: latheRecipePack
  id: SecurityEquipmentStaticGoob
  recipes:
  - GrenadeFlashBang
  - BolaEnergy

- type: latheRecipePack
  id: SecurityHypoStatic
  recipes:
  - CartridgeEpinephrine
  - CartridgeBicaridine
  - CartridgeDermaline
  - CartridgeAtropine
  - CartridgeSaline
  - SecHypo

## Dynamic
- type: latheRecipePack
  id: SecurityWeaponsGoob
  recipes:
  - Terminus
  - WeaponSubMachineSmart
  - WeaponEnergyRifle
  - WeaponEnergyIonRifle

- type: latheRecipePack
  id: SecurityAmmoGoob
  recipes:
  - EnergyMagRifleOverchargeLethal
  - EnergyMagRifleIon
  - EnergyMagRifleDisabler
  - EnergyMagRifleLethal
  - MagazineSmart
  - MagazineBoxShotgunIncendiaryHighCaliber
  - MagazineBoxShotgunBeanbagHighCaliber
  - MagazineBoxShotgunUraniumHighCaliber

- type: latheRecipePack
  id: SecurityEquipmentDynamicGoob
  recipes:
  - HoloprojectorSecurityAdvanced

- type: latheRecipePack
  id: SecurityCybernetics
  parent: MedicalCybernetics
  recipes:
  - SecurityCyberneticEyes