#

- type: latheRecipePack
  id: ServiceBoardsEvilStatic # emag-locked
  recipes:
  - SyndicateMicrowaveMachineCircuitboard

- type: latheRecipePack
  id: ServiceWeapons
  recipes:
  - WeaponLaserSvalinn

- type: latheRecipePack
  id: TapeRecorderStatic
  recipes:
  - CassetteTape
  - TapeRecorder
