- type: randomHumanoidSettings
  id: VisitorCaptainFake
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: job-name-cuptain
      description: job-description-cuptain
    - type: Loadout
      prototypes: [ CaptainFakeGear ]
      roleLoadout: [ RoleSurvivalStandard ]
  special:
  - !type:AddImplantSpecial
    implants: [ FakeMindShieldImplant ]