# For use by Role Types
# Do not touch these


#I touched em - Midna


# If you change/add a color here, also change it in role-types.ftl!

- type: roleType
  id: CrewAligned
  name: role-type-crew-aligned-name
  color: '#008000'
  symbol: "🛡"

- type: roleType
  id: NonAntagonist
  name: role-type-non-antagonist-name
  color: '#eeeeee'
  symbol: "🎭"
  
- type: roleType
  id: MinorAntagonist
  name: role-type-minor-antagonist-name
  color: '#d82000'
  symbol: "🗡"

- type: roleType
  id: ModerateAntagonist
  name: role-type-moderate-antagonist-name
  color: '#d82000'
  symbol: "⚔"

- type: roleType
  id: MajorAntagonist
  name: role-type-major-antagonist-name
  color: '#d82000'
  symbol: "💥" 

- type: roleType
  id: FreeAgent
  name: role-type-free-agent-name
  color: '#ffff00'
  symbol: "☯"

- type: roleType
  id: Familiar
  name: role-type-familiar-name
  color: '#6495ed'
  symbol: "🗡" # Should never be antag, but just in case.

- type: roleType
  id: Silicon
  name: role-type-silicon-name
  color: '#6495ed'
  symbol: "🗡" # Should never be antag, but just in case.

- type: roleType
  id: SiliconAntagonist
  name: role-type-silicon-antagonist-name
  color: '#c832e6'
  symbol: "⛞"
