#

- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10 hours - Goobstation
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10h Goobstation
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 90000 # 25 hours - Goobstation
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10h Goobstation
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 18000 # 5h Goobstation
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 90000 # 25 hours - Goobstation
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10h Goobstation
  - !type:DepartmentTimeRequirement
    department: Command
    time: 18000 # 5h Goobstation
  # should be changed to nukie playtime when thats tracked (wyci)
  guides: [ NuclearOperatives ]

- type: startingGear
  id: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesNightVisionGogglesNukie # Goobstation
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    #outerClothing: ClothingOuterHardsuitSyndie # goobstation - duke nukies
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDANukie # Goobstation
    pocket2: PlushieCarp
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio225TC # Goobstation - Telecrystal rework

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    neck: SyndicateWhistle
    pocket2: BaseUplinkRadio350TC # goobstation - im rich :fire::fire:
    #outerClothing: ClothingOuterHardsuitSyndieCommander # goobstation - duke nukies
  inhand:
  - NukeOpsDeclarationOfWar

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    back: ClothingBackpackDuffelSyndicateMedical # Goobstation
    eyes: ClothingEyesNightVisionGogglesNukie # Goobstation
    #outerClothing: ClothingOuterHardsuitSyndieMedic # goobstation - duke nukies
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiAgentPDA
    belt: ClothingBeltChemBagSyndiFilled # Goobstation
    pocket2: BaseUplinkRadio225TCMedic
  storage:
    back:
    - SyndiHypo
    #- SawAdvanced # Shitmed
    #- Cautery # Shitmed
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    #- HandheldHealthAnalyzer # Goobstation
    - CombatMedipen
    - DeathAcidifierImplanter
    - MedkitCombatFilled # Goobstation

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    # Goobstation - Telecrystal rework
    pocket2: BaseUplinkRadio350TC
