#

- type: entity
  name: tracker box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxTracker
  description: A box containing a couple trackers.
  components:
  - type: StorageFill
    contents:
    - id: TrackingImplanter # Todo - Replace with biochip?
      amount: 4
  - type: Sprite
    layers:
    - state: box

- type: entity
  name: lethal injections box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxLethalInjection
  description: A box containing several lethal injection syringes.
  components:
  - type: StorageFill
    contents:
    - id: SyringePoisonLethalInjection
      amount: 3
  - type: Sprite
    layers:
    - state: box

- type: entity
  name: 40mm baton grenade box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxGrenadesBaton
  description: A box containing eight 40mm baton grenades for single target stunning.
  components:
  - type: StorageFill
    contents:
    - id: GrenadeBaton
      amount: 8
  - type: Storage
    grid:
    - 0,0,3,3
    whitelist:
      tags:
      - Grenade

- type: entity
  name: 40mm flash grenade box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxGrenadesFlash
  description: A box containing eight 40mm flashbang grenades for mass target stunning.
  components:
  - type: StorageFill
    contents:
    - id: GrenadeFlash
      amount: 8
  - type: Storage
    grid:
    - 0,0,3,3
    whitelist:
      tags:
      - Grenade

- type: entity
  name: 40mm tear gas grenade box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxGrenadesTeargas
  description: A box containing eight 40mm tear gas grenades for efficient riot dispersion.
  components:
  - type: StorageFill
    contents:
    - id: GrenadeTeargas
      amount: 8
  - type: Storage
    grid:
    - 0,0,3,3
    whitelist:
      tags:
      - Grenade
