#

- type: antag
  id: Devil
  name: roles-antag-devil-name
  antagonist: true
  setPreference: true
  objective: roles-antag-devil-description
  guides: [ Devil ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # 30h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: JobLawyer
    time: 3600 # 1 Hour

- type: startingGear
  id: DevilStartingGear
  storage:
    back:
    - GuidebookCodexUmbra
    - PenDevil
    - ClothingEyesGlassesSunglasses
    - ClothingUniformJumpsuitDevil
